"""Shared utilities for the AI devs repository."""

from .ag3nts import (
    AG3NTS_ACCESS_LEVEL_URL,
    AG3NTS_BASE_URL,
    AG3NTS_LOCATION_URL,
    AG3NTS_PACKAGES_URL,
    AG3NTS_PUBLIC_DATA_BASE_URL,
    AG3NTS_RAILWAY_URL,
    AG3NTS_SHELL_URL,
    AG3NTS_TASK_DATA_BASE_URL,
    AG3NTS_VERIFY_URL,
    AG3NTS_ZMAIL_URL,
    build_ag3nts_public_data_url,
    build_ag3nts_task_data_url,
    build_task_answer_payload,
    submit_task_answer,
)
from .env import (
    find_repo_root,
    get_env,
    get_int_env,
    get_optional_env,
    load_repo_env,
    parse_env_file,
)
from .files import read_text_with_fallback, resolve_path, write_json
from .flags import extract_flag
from .http import HttpRequestError, JsonResponseError, get_bytes, get_json, get_text, post_json
from .logging import configure_logging, logger
from .openrouter import (
    ChatCompletionResult,
    OpenRouterClient,
    OpenRouterConfig,
    OpenRouterError,
    ToolCall,
    extract_completion_result,
    extract_text_content,
    extract_tool_calls,
)

__all__ = [
    "ChatCompletionResult",
    "HttpRequestError",
    "JsonResponseError",
    "OpenRouterClient",
    "OpenRouterConfig",
    "OpenRouterError",
    "ToolCall",
    "AG3NTS_ACCESS_LEVEL_URL",
    "AG3NTS_BASE_URL",
    "AG3NTS_LOCATION_URL",
    "AG3NTS_PACKAGES_URL",
    "AG3NTS_PUBLIC_DATA_BASE_URL",
    "AG3NTS_RAILWAY_URL",
    "AG3NTS_SHELL_URL",
    "AG3NTS_TASK_DATA_BASE_URL",
    "AG3NTS_VERIFY_URL",
    "AG3NTS_ZMAIL_URL",
    "build_ag3nts_public_data_url",
    "build_ag3nts_task_data_url",
    "build_task_answer_payload",
    "configure_logging",
    "extract_completion_result",
    "extract_flag",
    "extract_text_content",
    "extract_tool_calls",
    "find_repo_root",
    "get_bytes",
    "get_env",
    "get_int_env",
    "get_json",
    "get_optional_env",
    "get_text",
    "load_repo_env",
    "logger",
    "parse_env_file",
    "post_json",
    "read_text_with_fallback",
    "resolve_path",
    "submit_task_answer",
    "write_json",
]
